apiVersion: v1
kind: Secret
metadata:
  name: {{ template "api.secretName" . }}
type: Opaque
data:
  Mongo__User: {{ index .Values.mongodb.auth.usernames 0 | b64enc | quote }}
  Mongo__Password: {{ index .Values.mongodb.auth.passwords 0 | b64enc | quote }}