apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "api.configmapName" . }}
data:
  Mongo__Host: {{ template "mongodb.serviceName" . }}
  Mongo__DataBase: {{ index .Values.mongodb.auth.databases 0 }}